version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    user: '1000'
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./.mysql-data:/var/lib/mysql
      - ./sql-lab.sql:/docker-entrypoint-initdb.d/database.sql
